trigger: none 
pool: agent-hnp
variables: 
- group: New variable group 21-Apr
stages:
-   stage: scanstage
    displayName: scan chalega mast wala
    jobs:
      - job: scanjob
        steps:
        - task: PowerShell@2
          displayName: biome se karengey lint
          inputs:
            targetType: 'inline'
            script: 'C:\Hannumunnu\DevOps\DevOps\Tools\biome-win32-x64 lint $(System.DefaultWorkingDirectory)'

-   stage: sonarqube
    condition: always()
    jobs:
      - job: sonarqube
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                npm install -g @sonar/scan
                
                sonar -D sonar.host.url=http://localhost:9000 -D sonar.token=$(sonar_token) -D sonar.projectKey=hnp-21apr-project